name: Mushdamma
favicon: null
layout_spectrum: 0.9897111281752586
typography_spectrum: 0.4158237574156374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4574972928967327
  lightness: 0.6413139242213219
  saturation: 0.9748256537131965
  rhythmicContrast: 0.23508046916685998
purpose: []
